# Generated by Django 3.2.4 on 2021-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedjango', '0002_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
