# Generated by Django 3.2.4 on 2021-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedjango', '0005_auto_20210615_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
