# Generated by Django 3.2.4 on 2021-06-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuedjango', '0006_alter_account_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='myaccount',
        ),
    ]
